export const SIGN_IN_INIT = 'SIGN_IN_INIT';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_USER_INIT = 'GET_USER_INIT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const SIGN_OUT = 'SIGN_OUT';

export const SIGN_UP_INIT = 'SIGN_UP_INIT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const CREATE_FINGERPRINT_INIT = 'CREATE_FINGERPRINT_INIT';
export const CREATE_FINGERPRINT_SUCCESS = 'CREATE_FINGERPRINT_SUCCESS';
export const CREATE_FINGERPRINT_ERROR = 'CREATE_FINGERPRINT_ERROR';

export const SCAN_FINGERPRINT_INIT = 'SCAN_FINGERPRINT_INIT';
export const SCAN_FINGERPRINT_SUCCESS = 'SCAN_FINGERPRINT_SUCCESS';
export const SCAN_FINGERPRINT_ERROR = 'SCAN_FINGERPRINT_ERROR';
