export const GET_USER_GROUPS_INIT = 'GET_USER_GROUPS_INIT';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_ERROR = 'GET_USER_GROUPS_ERROR';

export const CHANGE_CURRENT_GROUP = 'CHANGE_CURRENT_GROUP';

export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_ERROR = 'LEAVE_GROUP_ERROR';
